---
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ $.Values.namespace.name }}
  labels:
{{ include "sqlserver.selectorLabels" . | indent 4 }}
  annotations:
    {{- if .Values.argocd.enabled }}
    argocd.argoproj.io/sync-wave: "10"
    {{- end }}
{{ include "sqlserver.customProjectAnnotations" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      securityContext:
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image }}
          ports:
            - containerPort: 1433
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql
                  key: MSSQL_SA_PASSWORD

          # IfNotPresent | Always | Never
          imagePullPolicy: IfNotPresent

          resources:
{{- toYaml .Values.deployment.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: sqlserverdb
              mountPath: /var/opt/mssql
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      # serviceAccount: {{ include "sqlserver.nameWithSuffix" (dict "context" . "suffix" (.Values.serviceAccount.name | default "sa"))  }}
      # serviceAccountName: {{ include "sqlserver.nameWithSuffix" (dict "context" . "suffix" (.Values.serviceAccount.name | default "sa"))  }}
      volumes:
        - name: sqlserverdb
          persistentVolumeClaim:
            claimName: {{ include "sqlserver.nameWithSuffix" (dict "context" $ "suffix" .Values.pvcs.ocs.name) }}
---
